"""
test_table_ridge.py
===================
Consistency tests for the ridge/OLS sweep table (`tables/table_ridge.tex`,
tab:ridge, generated by `scripts/ridge_baseline_test.py`, Step 13), which
the appendix includes.

Pins tex <-> csv agreement (the -0.57 stale-caption incident), the row
labels, and the appendix inclusion.
"""

import os
import re
import sys

import pandas as pd
import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
if REPO not in sys.path:
    sys.path.insert(0, REPO)

CSV_PATH = os.path.join(REPO, 'tables', 'table_ridge.csv')
TEX_PATH = os.path.join(REPO, 'tables', 'table_ridge.tex')
APPENDIX_PATH = os.path.join(REPO, 'latex', 'appendix.tex')


@pytest.fixture(scope='module')
def csv():
    return pd.read_csv(CSV_PATH)


@pytest.fixture(scope='module')
def tex():
    with open(TEX_PATH) as f:
        return f.read()


def test_csv_schema_and_row_count(csv):
    assert list(csv.columns) == ['model', 'alpha', 'sharpe', 'ann_ret',
                                 'ann_vol', 'mdd', 'sr_calm', 'sr_panic']
    # OLS + 6 ridge alphas + LR + XGB
    assert len(csv) == 9
    assert (csv['model'] == 'Ridge').sum() == 6


def test_csv_has_ols_lr_xgb_rows(csv):
    models = set(csv['model'])
    assert 'OLS (no reg.)' in models
    assert any(m.startswith('LR') for m in models)
    assert 'XGB' in models


def test_tex_lr_label_is_clean(tex):
    assert 'LR (LR, classification)' not in tex
    assert 'LR (classification)' in tex


def test_tex_midrule_separates_ridge_block_from_lr_xgb(tex):
    assert '\\midrule\nLR (classification)' in tex


def test_tex_ols_sharpe_matches_csv(csv, tex):
    ols_sharpe = csv.loc[csv['model'] == 'OLS (no reg.)', 'sharpe'].iloc[0]
    m = re.search(r'^OLS \(no reg\.\) & --- & (\$-\$)?([0-9.]+) &', tex,
                  re.MULTILINE)
    assert m, 'OLS row not found in table_ridge.tex'
    tex_sharpe = float(m.group(2)) * (-1 if m.group(1) else 1)
    assert tex_sharpe == pytest.approx(round(ols_sharpe, 2))


def test_caption_sharpe_matches_ols_row(csv, tex):
    """The caption quotes the OLS/ridge Sharpe; it must match the data
    (regression guard for the stale $-$0.57 caption)."""
    ols_sharpe = csv.loc[csv['model'] == 'OLS (no reg.)', 'sharpe'].iloc[0]
    m = re.search(r'Sharpe of \$-\$([0-9.]+)', tex)
    assert m, 'caption does not quote the Sharpe'
    assert float(m.group(1)) == pytest.approx(abs(round(ols_sharpe, 2)))


def test_table_ridge_not_included_in_thesis():
    """Per Gilad's decision (2026-07-05) the ridge sweep stays a diagnostic
    artifact: OLS appears as a row in tab:performance only, and
    table_ridge is NOT \\input anywhere in the thesis."""
    latex_dir = os.path.join(REPO, 'latex')
    tex_files = [os.path.join(REPO, 'main.tex')] + [
        os.path.join(latex_dir, f) for f in os.listdir(latex_dir)
        if f.endswith('.tex')
    ]
    for path in tex_files:
        with open(path) as f:
            assert 'table_ridge' not in f.read(), \
                f'{path} references table_ridge'
