"""
build_table_cluster_k4_leg_betas.py
=====================================
Generates tables/table_cluster_k4_leg_betas.tex for thesis §5.2.
Reads results/thesis/cluster_k4_leg_betas.csv and emits a booktabs table
with side-by-side M2 and Fixed 12-mo momentum leg-level CAPM betas per
K=4 cluster, with standard errors in parentheses and beta spread.

Run:
    python scripts/build_table_cluster_k4_leg_betas.py

Output:
    tables/table_cluster_k4_leg_betas.tex
"""

import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from config import RESULTS_THESIS_DIR, TABLES_DIR

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
INPUT_PATH = os.path.join(RESULTS_THESIS_DIR, 'cluster_k4_leg_betas.csv')
TEX_PATH   = os.path.join(TABLES_DIR, 'table_cluster_k4_leg_betas.tex')

CLUSTER_LABELS = {
    0: 'calm continuation',
    1: 'mild continuation',
    2: 'post-panic recovery',
    3: 'deep crisis',
}

EXPECTED_COLS = {
    'cluster', 'n_months',
    'm2_beta_long', 'm2_se_long', 'm2_beta_short', 'm2_se_short', 'm2_beta_spread',
    'fixed_beta_long', 'fixed_se_long', 'fixed_beta_short', 'fixed_se_short',
    'fixed_beta_spread',
}


def _fmt_beta(beta, se):
    """Format beta with SE in parentheses."""
    if np.isnan(beta):
        return '---'
    sign = '$-$' if beta < 0 else ''
    se_str = f'({se:.2f})' if not np.isnan(se) else ''
    return f'{sign}{abs(beta):.2f} {se_str}'


def _fmt_spread(spread):
    """Format spread value with sign."""
    if np.isnan(spread):
        return '---'
    sign = '$-$' if spread < 0 else r'\phantom{$-$}'
    return f'{sign}{abs(spread):.2f}'


def main():
    # ------------------------------------------------------------------
    # Load and validate inputs
    # ------------------------------------------------------------------
    if not os.path.exists(INPUT_PATH):
        raise FileNotFoundError(
            f'{INPUT_PATH} not found. Run the cluster leg-beta script first.'
        )

    df = pd.read_csv(INPUT_PATH)
    missing = EXPECTED_COLS - set(df.columns)
    if missing:
        raise ValueError(f'cluster_k4_leg_betas.csv missing columns: {missing}')

    df = df.sort_values('cluster').reset_index(drop=True)
    print(f'Loaded {len(df)} clusters')

    # ------------------------------------------------------------------
    # Build LaTeX rows
    # ------------------------------------------------------------------
    data_rows = []
    for _, row in df.iterrows():
        k = int(row['cluster'])
        label = CLUSTER_LABELS[k]
        n = int(row['n_months'])

        m2_long   = _fmt_beta(row['m2_beta_long'],    row['m2_se_long'])
        m2_short  = _fmt_beta(row['m2_beta_short'],   row['m2_se_short'])
        m2_spread = _fmt_spread(row['m2_beta_spread'])

        fx_long   = _fmt_beta(row['fixed_beta_long'],  row['fixed_se_long'])
        fx_short  = _fmt_beta(row['fixed_beta_short'], row['fixed_se_short'])
        fx_spread = _fmt_spread(row['fixed_beta_spread'])

        data_rows.append(
            f'    {k+1} ({label}) & {n}'
            f' & {m2_long} & {m2_short} & {m2_spread}'
            f' & {fx_long} & {fx_short} & {fx_spread} \\\\'
        )

    # ------------------------------------------------------------------
    # Assemble .tex
    # ------------------------------------------------------------------
    caption = (
        r'Leg-level CAPM betas by K=4 cluster, 2011--2024 test period. '
        r'M2 (regime-conditional XGB ensemble) versus unconditional 12-month momentum, '
        r'side-by-side. '
        r'Standard errors in parentheses. '
        r'Spread $= \beta_L - \beta_S$.'
    )

    tex_lines = [
        r'% Auto-generated by scripts/build_table_cluster_k4_leg_betas.py -- DO NOT HAND EDIT.',
        r'\begin{table}[H]',
        r'\centering',
        r'\small',
        r'\begin{tabular}{l r | l l r | l l r}',
        r'\toprule',
        r' & & \multicolumn{3}{c|}{M2 (XGB ensemble)} & \multicolumn{3}{c}{Fixed 12-mo mom} \\',
        r'\cmidrule(lr){3-5} \cmidrule(lr){6-8}',
        r'Cluster & $n$ & $\beta_L$ & $\beta_S$ & Spread & $\beta_L$ & $\beta_S$ & Spread \\',
        r'\midrule',
    ]
    tex_lines.extend(data_rows)
    tex_lines += [
        r'\bottomrule',
        r'\end{tabular}',
        f'\\caption{{{caption}}}',
        r'\label{tab:cluster_k4_leg_betas}',
        r'\end{table}',
    ]

    # ------------------------------------------------------------------
    # Write output
    # ------------------------------------------------------------------
    os.makedirs(TABLES_DIR, exist_ok=True)
    with open(TEX_PATH, 'w') as f:
        f.write('\n'.join(tex_lines) + '\n')

    print(f'Wrote {TEX_PATH}')


if __name__ == '__main__':
    main()
