"""
build_table_cluster_k4_shap_shares.py
=======================================
Generates tables/table_cluster_k4_shap_shares.tex for thesis §5.2.
Reads results/thesis/cluster_k4_shap_shares.csv and emits a booktabs table
with per-cluster pi^filter SHAP share breakdown (long-leg, short-leg,
combined).

Run:
    python scripts/build_table_cluster_k4_shap_shares.py

Output:
    tables/table_cluster_k4_shap_shares.tex
"""

import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from config import RESULTS_THESIS_DIR, TABLES_DIR

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
INPUT_PATH = os.path.join(RESULTS_THESIS_DIR, 'cluster_k4_shap_shares.csv')
TEX_PATH   = os.path.join(TABLES_DIR, 'table_cluster_k4_shap_shares.tex')

CLUSTER_LABELS = {
    0: 'calm continuation',
    1: 'mild continuation',
    2: 'post-panic recovery',
    3: 'deep crisis',
}

EXPECTED_COLS = {
    'cluster', 'n_months',
    'pi_share_long', 'pi_share_short', 'pi_share_combined',
}


def _fmt_pct(x):
    """Format a [0,1] fraction as percentage to 1 d.p."""
    if np.isnan(x):
        return '---'
    return f'{x * 100:.1f}\\%'


def main():
    # ------------------------------------------------------------------
    # Load and validate inputs
    # ------------------------------------------------------------------
    if not os.path.exists(INPUT_PATH):
        raise FileNotFoundError(
            f'{INPUT_PATH} not found. Run the cluster SHAP-share script first.'
        )

    df = pd.read_csv(INPUT_PATH)
    missing = EXPECTED_COLS - set(df.columns)
    if missing:
        raise ValueError(f'cluster_k4_shap_shares.csv missing columns: {missing}')

    df = df.sort_values('cluster').reset_index(drop=True)
    print(f'Loaded {len(df)} clusters')

    # ------------------------------------------------------------------
    # Build LaTeX rows
    # ------------------------------------------------------------------
    data_rows = []
    for _, row in df.iterrows():
        k = int(row['cluster'])
        label = CLUSTER_LABELS[k]
        n = int(row['n_months'])
        long_share  = _fmt_pct(row['pi_share_long'])
        short_share = _fmt_pct(row['pi_share_short'])
        comb_share  = _fmt_pct(row['pi_share_combined'])

        data_rows.append(
            f'    {k+1} ({label}) & {n}'
            f' & {long_share} & {short_share} & {comb_share} \\\\'
        )

    # ------------------------------------------------------------------
    # Assemble .tex
    # ------------------------------------------------------------------
    caption = (
        r"$\pi^{\text{filter}}$'s SHAP share by K=4 cluster, 2011--2024 test period. "
        r'Long and short shares are computed over long-leg and short-leg picks respectively; '
        r'combined is over all stock-months in the cluster.'
    )

    tex_lines = [
        r'% Auto-generated by scripts/build_table_cluster_k4_shap_shares.py -- DO NOT HAND EDIT.',
        r'\begin{table}[H]',
        r'\centering',
        r'\small',
        r'\begin{tabular}{l r r r r}',
        r'\toprule',
        r'Cluster & $n$ & Long $\\pi$ share & Short $\\pi$ share & Combined $\\pi$ share \\',
        r'\midrule',
    ]
    tex_lines.extend(data_rows)
    tex_lines += [
        r'\bottomrule',
        r'\end{tabular}',
        f'\\caption{{{caption}}}',
        r'\label{tab:cluster_k4_shap_shares}',
        r'\end{table}',
    ]

    # ------------------------------------------------------------------
    # Write output
    # ------------------------------------------------------------------
    os.makedirs(TABLES_DIR, exist_ok=True)
    with open(TEX_PATH, 'w') as f:
        f.write('\n'.join(tex_lines) + '\n')

    print(f'Wrote {TEX_PATH}')


if __name__ == '__main__':
    main()
