"""
build_table_cluster_k4_descriptors.py
======================================
Generates tables/table_cluster_k4_descriptors.tex for thesis §5.2.
Reads results/thesis/cluster_k4_descriptor_table.csv (main descriptors) and
results/thesis/cluster_k4_downside_metrics.csv (Sortino + max drawdown) and
emits a booktabs table with per-cluster regime labels, n, pi_bar, Sharpe with
CI, hit rate, Sortino, and max drawdown.

Run:
    python scripts/build_table_cluster_k4_descriptors.py

Output:
    tables/table_cluster_k4_descriptors.tex
"""

import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from config import RESULTS_THESIS_DIR, TABLES_DIR

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
DESCRIPTORS_PATH    = os.path.join(RESULTS_THESIS_DIR, 'cluster_k4_descriptor_table.csv')
DOWNSIDE_PATH       = os.path.join(RESULTS_THESIS_DIR, 'cluster_k4_downside_metrics.csv')
TEX_PATH            = os.path.join(TABLES_DIR, 'table_cluster_k4_descriptors.tex')

CLUSTER_LABELS = {
    0: 'calm continuation',
    1: 'mild continuation',
    2: 'post-panic recovery',
    3: 'deep crisis',
}

EXPECTED_COLS_DESC = {
    'cluster', 'n_months', 'pi_panic_mean', 'sharpe', 'sharpe_lo95',
    'sharpe_hi95', 'hit_rate',
}
EXPECTED_COLS_DOWN = {'cluster', 'max_drawdown', 'sortino_ratio'}


def _fmt_sharpe(x):
    """Format Sharpe to 2 d.p., math minus for negatives."""
    if np.isnan(x):
        return '---'
    return f'$-${abs(x):.2f}' if x < 0 else f'{x:.2f}'


def _fmt_pct(x):
    """Format a [0,1] fraction as a percentage to 1 d.p."""
    if np.isnan(x):
        return '---'
    pct = x * 100
    sign = '-' if pct < 0 else ''
    return f'{sign}{abs(pct):.1f}\\%'


def _fmt_2dp(x):
    """Format to 2 d.p., math minus for negatives."""
    if np.isnan(x):
        return '---'
    return f'$-${abs(x):.2f}' if x < 0 else f'{x:.2f}'


def main():
    # ------------------------------------------------------------------
    # Load and validate inputs
    # ------------------------------------------------------------------
    for path in [DESCRIPTORS_PATH, DOWNSIDE_PATH]:
        if not os.path.exists(path):
            raise FileNotFoundError(
                f'{path} not found. Run the cluster descriptor scripts first.'
            )

    desc = pd.read_csv(DESCRIPTORS_PATH)
    down = pd.read_csv(DOWNSIDE_PATH)

    missing_desc = EXPECTED_COLS_DESC - set(desc.columns)
    if missing_desc:
        raise ValueError(f'cluster_k4_descriptor_table.csv missing columns: {missing_desc}')

    missing_down = EXPECTED_COLS_DOWN - set(down.columns)
    if missing_down:
        raise ValueError(f'cluster_k4_downside_metrics.csv missing columns: {missing_down}')

    # Merge on cluster
    df = desc.merge(down[['cluster', 'max_drawdown', 'sortino_ratio']], on='cluster')
    df = df.sort_values('cluster').reset_index(drop=True)
    print(f'Loaded {len(df)} clusters')

    # ------------------------------------------------------------------
    # Build LaTeX rows
    # ------------------------------------------------------------------
    data_rows = []
    for _, row in df.iterrows():
        k = int(row['cluster'])
        label = CLUSTER_LABELS[k]
        n = int(row['n_months'])
        pi_bar = f"{row['pi_panic_mean']:.2f}"
        sharpe_str = (
            f"{_fmt_sharpe(row['sharpe'])} "
            f"[{_fmt_sharpe(row['sharpe_lo95'])}, {_fmt_sharpe(row['sharpe_hi95'])}]"
        )
        hit = _fmt_pct(row['hit_rate'])
        sortino = _fmt_2dp(row['sortino_ratio'])
        mdd = _fmt_pct(-abs(row['max_drawdown']))  # drawdown is positive in CSV, show as negative

        data_rows.append(
            f"    {k+1} ({label}) & {n} & {pi_bar} & {sharpe_str} "
            f"& {hit} & {sortino} & {mdd} \\\\"
        )

    # ------------------------------------------------------------------
    # Assemble .tex
    # ------------------------------------------------------------------
    caption = (
        r'K=4 cluster descriptors, 2011--2024 test period, '
        r'$n_{\text{total}} = 167$ months. '
        r'Sharpes are annualised and computed via block bootstrap with block size 6, '
        r'5{,}000 reps. '
        r'Hit rate is the fraction of cluster months with positive M2 return. '
        r"Maximum drawdown is the peak-to-trough drawdown within the cluster's "
        r'chronological subseries. '
        r'Sortino uses downside std (negative-return std) in the denominator.'
    )

    tex_lines = [
        r'% Auto-generated by scripts/build_table_cluster_k4_descriptors.py -- DO NOT HAND EDIT.',
        r'\begin{table}[H]',
        r'\centering',
        r'\small',
        r'\begin{tabular}{l r r l r r r}',
        r'\toprule',
        r'Cluster & $n$ & $\bar{\pi}$ & Sharpe [95\% CI] & Hit rate & Sortino & Max DD \\',
        r'\midrule',
    ]
    tex_lines.extend(data_rows)
    tex_lines += [
        r'\bottomrule',
        r'\end{tabular}',
        f'\\caption{{{caption}}}',
        r'\label{tab:cluster_k4_descriptors}',
        r'\end{table}',
    ]

    # ------------------------------------------------------------------
    # Write output
    # ------------------------------------------------------------------
    os.makedirs(TABLES_DIR, exist_ok=True)
    with open(TEX_PATH, 'w') as f:
        f.write('\n'.join(tex_lines) + '\n')

    print(f'Wrote {TEX_PATH}')


if __name__ == '__main__':
    main()
