"""
compose_step_k_report.py
========================
Generates `results/STEP_K_REPORT.md` — the FINAL summary report that
Gilad reviews before greenlighting any thesis edits.

Composes content from:
  - the existing Step F first-checkpoint report (Shumway diff + leg-betas)
  - US CV winners: `results/xgb_cv_winner.json`, `results/hmm_cv_winner.json`
  - UK/JP production results: `results/intl_{uk,jp}_summary{,_uspi}.csv`
  - the Step L prose-edit checklist (`results/PROSE_EDITS.md`) is
    REFERENCED but produced separately — Step K just points at it.

Run AFTER Phase 2 lanes complete (US Step J + UK/JP Step N2 done) and
BEFORE any `latex/*.tex` edit. Read-only on the thesis.

Usage
-----
    python scripts/compose_step_k_report.py \\
        --baseline-dir baseline_pre_shumway_20260426_150517 \\
        --output results/STEP_K_REPORT.md
"""

import argparse
import json
import os
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
os.chdir(REPO)


def _load_json(path):
    if not Path(path).exists():
        return None
    with open(path) as f:
        return json.load(f)


def _load_csv(path):
    if not Path(path).exists():
        return None
    return pd.read_csv(path)


def _format_xgb_winner(w):
    if w is None:
        return '_pending — `results/xgb_cv_winner.json` not yet present_'
    out = [
        f"- depth = **{w.get('max_depth', '?')}**",
        f"- learning_rate = **{w.get('learning_rate', '?')}**",
        f"- n_estimators = **{w.get('n_estimators', '?')}**",
        f"- mean val Sharpe = **{w.get('mean_val_sharpe', float('nan')):+.3f}**"
        + f" (fold-std {w.get('fold_std_val_sharpe', float('nan')):.3f},"
        + f" {w.get('n_folds', '?')} folds)",
        f"- ensemble seeds per cell: {w.get('n_seeds_per_cell', '?')}",
        f"- transaction fee: {w.get('fee_decimal', float('nan')):.4f}",
    ]
    pf = w.get('per_fold_val_sharpe', {})
    if pf:
        out.append('- per-fold val Sharpes:')
        for fold, sh in sorted(pf.items()):
            out.append(f'    - fold {fold}: {sh:+.3f}')
    return '\n'.join(out)


def _format_hmm_winner(w):
    if w is None:
        return '_pending — `results/hmm_cv_winner.json` not yet present_'
    out = [
        f"- combo = **`{w.get('combo', '?')}`**"
        + f" ({w.get('n_features', '?')} features)",
        f"- mean val Sharpe = **{w.get('mean_val_sharpe', float('nan')):+.3f}**"
        + f" (fold-std {w.get('fold_std_val_sharpe', float('nan')):.3f},"
        + f" {w.get('n_folds', '?')} folds)",
        f"- HMM seeds per cell: {w.get('n_hmm_seeds', '?')}",
        f"- XGB seeds per ensemble: {w.get('n_xgb_seeds', '?')}",
        f"- transaction fee: {w.get('fee_decimal', float('nan')):.4f}",
    ]
    pf = w.get('per_fold_val_sharpe', {})
    if pf:
        out.append('- per-fold val Sharpes:')
        for fold, sh in sorted(pf.items()):
            out.append(f'    - fold {fold}: {sh:+.3f}')
    return '\n'.join(out)


def _format_intl_summary(region):
    """Return a 4-row markdown table for a region (regional pi vs US pi)."""
    reg = _load_csv(REPO / 'results' / f'intl_{region}_summary.csv')
    uspi = _load_csv(REPO / 'results' / f'intl_{region}_summary_uspi.csv')
    if reg is None or uspi is None:
        return f'_pending — `results/intl_{region}_summary*.csv` not yet present_'

    def _row(name, df):
        sub = df[df['strategy'] == name]
        if sub.empty:
            return None
        r = sub.iloc[0]
        return (f'{r["sharpe"]:+.3f}', f'{r["ann_ret"] * 100:+.1f}%',
                f'{r["ann_vol"] * 100:.1f}%', f'{r["max_dd"] * 100:+.1f}%')

    lines = [
        '| Strategy | Sharpe (regional π) | Sharpe (US π, Test A) |'
        ' Ann.Ret (US π) | MDD (US π) |',
        '|---|---|---|---|---|',
    ]
    for strat in ['market', 'fixed_mom_12', 'method0_formula',
                  'method1_lr', 'method2_xgb']:
        reg_row = _row(strat, reg)
        uspi_row = _row(strat, uspi)
        if reg_row is None or uspi_row is None:
            continue
        lines.append(
            f'| `{strat}` | {reg_row[0]} | {uspi_row[0]} |'
            f' {uspi_row[1]} | {uspi_row[3]} |'
        )
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--baseline-dir', required=True)
    parser.add_argument('--output', default='results/reports/STEP_K_REPORT.md')
    args = parser.parse_args()

    baseline = Path(args.baseline_dir)
    if not baseline.is_dir():
        sys.exit(f'baseline dir not found: {baseline}')

    out_lines = [
        '# Step K — Final Report',
        '',
        f'Generated by `scripts/compose_step_k_report.py`.',
        f'Baseline (pre-Shumway): `{args.baseline_dir}`',
        '',
        '> This is the **final summary** before any `latex/*.tex` edit. '
        'See also `results/STEP_F_REPORT.md` (first checkpoint, Shumway '
        'diff + leg-betas) and `results/PROSE_EDITS.md` (line-by-line '
        'prose-update checklist from Step L).',
        '',
        '---',
        '',
        '## Part 1 — US CV winners (Phase 2 Lane A)',
        '',
        '### XGB hyperparameter CV (Step I)',
        '',
        _format_xgb_winner(_load_json(REPO / 'results' / 'xgb_cv_winner.json')),
        '',
        '### HMM feature-set CV (Step J)',
        '',
        _format_hmm_winner(_load_json(REPO / 'results' / 'hmm_cv_winner.json')),
        '',
        '---',
        '',
        '## Part 2 — UK/JP production results (Phase 2 Lane B)',
        '',
        '### United Kingdom',
        '',
        _format_intl_summary('uk'),
        '',
        '### Japan',
        '',
        _format_intl_summary('jp'),
        '',
        '---',
        '',
        '## Part 3 — Headline US numbers (recap from Step F)',
        '',
    ]

    # Read the Step F report verbatim if present (skip header lines)
    step_f_path = REPO / 'results' / 'STEP_F_REPORT.md'
    if step_f_path.exists():
        f_text = step_f_path.read_text().splitlines()
        # Find the first "## Part 1" line and copy from there until the
        # Step F-specific gates section
        copy_started = False
        for line in f_text:
            if line.startswith('## Part 1') and not copy_started:
                copy_started = True
            if copy_started:
                if line.startswith('## Gates respected'):
                    break
                out_lines.append(line)
    else:
        out_lines.append(
            '_Step F report (`results/STEP_F_REPORT.md`) not present; '
            'rerun `scripts/compose_step_f_report.py` first._'
        )

    out_lines += [
        '',
        '---',
        '',
        '## Part 4 — Pending thesis edits (gated)',
        '',
        '### Numeric prose updates',
        '',
        'See `results/PROSE_EDITS.md` for the line-by-line checklist '
        'produced by `scripts/build_prose_edit_list.py` (Step L). Each '
        'row is reviewed and ticked individually; `latex/*.tex` is NOT '
        'modified until each is greenlit.',
        '',
        '### Structural edit bundle (#1-#4)',
        '',
        'Per `NEXT_RUN_PLAN.md`, the leg-betas finding (Step E) decides '
        'whether the bundle lands as the "clean inversion" framing or '
        'the "cross-sectional re-ranking" reframe. See `STEP_F_REPORT.md` '
        'Part 2 for the inversion classification.',
        '',
        '- [ ] **Edit #1** — new "Leg-level beta dynamics across '
        'regimes" subsection in `latex/main_results.tex` (or reframe)',
        '- [ ] **Edit #2** — expand D&M beta in `latex/literature_review.tex:19`',
        '- [ ] **Edit #3** — sharpen "two channels" in `latex/conclusion.tex:53`',
        '- [ ] **Edit #4** — pi_filter ↔ D&M bear-indicator link in '
        '`latex/methodology.tex` (standalone)',
        '',
        '### CV-driven thesis updates',
        '',
        '- [ ] Update `latex/methodology.tex` and `latex/appendix.tex` '
        'with CV-based framing — replace the existing "test-set peek" '
        'language now that real CV winners are in.',
        '- [ ] Append `latex/data_section.tex` HMM feature-selection '
        'caveat → CV-justified statement using winner from `hmm_cv_winner.json`.',
        '',
        '### UK/JP integration',
        '',
        '- [ ] Append "International validation" section to `RESULTS_LOG.md` '
        '(NOT yet `latex/*.tex`).',
        '- [ ] Decide whether UK/JP findings land as headline ("global '
        'financial cycle channel" if US-pi beats regional pi in both '
        'regions) or as future-work caveat.',
        '',
        '---',
        '',
        '## Gates respected',
        '- ✅ G1: backtest PID 1752 exited before Step C',
        '- ✅ G2: baseline snapshot complete before Step C/D',
        '- ✅ G3: NO `latex/*.tex` edits made yet',
        '- ✅ G4: NO `git push` performed',
        '',
        '## 🛑 HARD STOP',
        '',
        'Awaiting Gilad greenlight before any `latex/*.tex` edit. Each '
        'row in `PROSE_EDITS.md` and each item in the structural-edit '
        'bundle is ticked individually.',
        '',
    ]

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text('\n'.join(out_lines) + '\n')
    print(f'Wrote: {out_path}')


if __name__ == '__main__':
    main()
