"""
compose_step_f_report.py
========================
Generates `results/STEP_F_REPORT.md` by reading the post-Shumway live
tables, the pre-Shumway snapshot tables, and the Step E leg-betas output,
and producing a side-by-side comparison.

Run after Step D (pipeline rerun) and Step E (leg-betas) complete.

Usage
-----
    python scripts/compose_step_f_report.py \\
        --baseline-dir baseline_pre_shumway_20260426_150517 \\
        --output results/STEP_F_REPORT.md
"""

import argparse
import os
import re
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
os.chdir(REPO)


def parse_table_row(tex_path, row_label, col_index):
    """Pull one cell from a tabular environment.

    Looks for a line whose first `&`-cell starts with `row_label`, then
    returns the `col_index`-th column (0-based)."""
    if not Path(tex_path).exists():
        return None
    with open(tex_path) as f:
        text = f.read()
    for raw in text.splitlines():
        body = raw.strip()
        if not body or body.startswith('%'):
            continue
        if r'\\' not in body:
            continue
        body = re.sub(r'\\\\\s*$', '', body)
        cells = [c.strip() for c in body.split('&')]
        if cells and row_label in cells[0]:
            if col_index < len(cells):
                return cells[col_index]
    return None


def _md_clean(s):
    """Strip LaTeX wrappers so markdown renders the value cleanly.

    `\\%` → `%`, `$-$` → `-`, trailing `\\\\` removed."""
    if s is None:
        return None
    s = re.sub(r'\\%', '%', s)
    s = re.sub(r'\$-\$', '-', s)
    s = re.sub(r'\\\\', '', s)
    return s.strip()


def fmt_delta(pre, post, fmt='auto'):
    """Compact formatter for a (pre, post) pair with delta column."""
    pre_clean = _md_clean(pre) if pre is not None else None
    post_clean = _md_clean(post) if post is not None else None
    if pre_clean is None and post_clean is None:
        return ('—', '—', '—')
    if pre_clean is None:
        return ('—', str(post_clean), 'NEW')
    if post_clean is None:
        return (str(pre_clean), '—', 'DROPPED')
    return (str(pre_clean), str(post_clean), '')


def maybe_float(s):
    """Strip LaTeX/percent decoration and try to parse as float."""
    if s is None:
        return None
    s = re.sub(r'\$-\$', '-', s)
    s = re.sub(r'\\%', '', s)
    s = re.sub(r'\\\\', '', s)
    s = re.sub(r'\*+', '', s)
    s = s.strip()
    try:
        return float(s)
    except ValueError:
        return None


def read_csv_first_row_for(strategy_pattern, csv_path, value_col):
    """Pull a value from a CSV row whose first column matches a pattern."""
    if not Path(csv_path).exists():
        return None
    df = pd.read_csv(csv_path)
    if value_col not in df.columns:
        return None
    name_col = df.columns[0]
    rows = df[df[name_col].astype(str).str.contains(strategy_pattern,
                                                    case=False, regex=True,
                                                    na=False)]
    if rows.empty:
        return None
    return rows.iloc[0][value_col]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--baseline-dir', required=True)
    parser.add_argument('--output',
                        default='results/STEP_F_REPORT.md')
    args = parser.parse_args()

    base = Path(args.baseline_dir)
    if not base.is_dir():
        sys.exit(f'baseline dir not found: {base}')
    base_tables = base / 'tables'
    live_tables = REPO / 'tables'

    out_lines = [
        '# Step F — First Checkpoint Report',
        '',
        f'Generated by `scripts/compose_step_f_report.py`.',
        f'Baseline (pre-Shumway): `{args.baseline_dir}`',
        f'Live (post-Shumway):    `tables/`',
        '',
        '---',
        '',
        '## Part 1 — Pipeline-rerun diff (Shumway impact)',
        '',
    ]

    # ── Headline numbers from table_performance.tex (M2: XGB row) ─────────────
    # Columns: Ann.Ret | Ann.Vol | Sharpe | Max DD | Beta | NW t | Final $
    M2 = 'M2: XGB'
    cols_perf = ['Ann.Ret', 'Ann.Vol', 'Sharpe', 'Max DD', 'Beta', 'NW t', 'Final $']

    out_lines.append('### Headline (M2: XGB, mom+π) — table_performance.tex')
    out_lines.append('')
    out_lines.append('| Metric | Pre | Post | Δ |')
    out_lines.append('|---|---|---|---|')
    for i, label in enumerate(cols_perf, start=1):
        pre = parse_table_row(base_tables / 'table_performance.tex', M2, i)
        post = parse_table_row(live_tables / 'table_performance.tex', M2, i)
        pre_f = maybe_float(pre)
        post_f = maybe_float(post)
        delta = ''
        if pre_f is not None and post_f is not None:
            delta = f'{post_f - pre_f:+.3g}'
        a, b, _ = fmt_delta(pre, post)  # already _md_clean'd inside fmt_delta
        out_lines.append(f'| {label} | {a} | {b} | {delta} |')
    out_lines.append('')

    # ── Regime Sharpe (calm/panic) ────────────────────────────────────────────
    out_lines.append('### Regime-conditional Sharpe — table_regime_sharpe.tex')
    out_lines.append('')
    out_lines.append('| Strategy | Pre Calm | Post Calm | Pre Panic | Post Panic |')
    out_lines.append('|---|---|---|---|---|')
    for strat in ['Market', 'Fixed 12-mo', 'M1: LR', 'M2: XGB']:
        pre_calm = _md_clean(parse_table_row(base_tables / 'table_regime_sharpe.tex', strat, 2))
        post_calm = _md_clean(parse_table_row(live_tables / 'table_regime_sharpe.tex', strat, 2))
        pre_pan = _md_clean(parse_table_row(base_tables / 'table_regime_sharpe.tex', strat, 3))
        post_pan = _md_clean(parse_table_row(live_tables / 'table_regime_sharpe.tex', strat, 3))
        out_lines.append(
            f'| {strat} | {pre_calm or "—"} | {post_calm or "—"} | '
            f'{pre_pan or "—"} | {post_pan or "—"} |'
        )
    out_lines.append('')

    # ── Sub-period Sharpes ────────────────────────────────────────────────────
    out_lines.append('### Sub-period Sharpe (M2: XGB) — table_subperiod.tex')
    out_lines.append('')
    out_lines.append('| Sub-period | Pre | Post |')
    out_lines.append('|---|---|---|')
    for col, label in enumerate(['2011-2015', '2016-2020', '2021-2025', 'Full'],
                                  start=1):
        pre = _md_clean(parse_table_row(base_tables / 'table_subperiod.tex', M2, col))
        post = _md_clean(parse_table_row(live_tables / 'table_subperiod.tex', M2, col))
        out_lines.append(f'| {label} | {pre or "—"} | {post or "—"} |')
    out_lines.append('')

    # ── Factor alphas (CAPM through FF6) ──────────────────────────────────────
    out_lines.append('### Factor alphas — table_factor_alphas.tex')
    out_lines.append('')
    out_lines.append('| Model | Pre α | Post α | Pre t | Post t |')
    out_lines.append('|---|---|---|---|---|')
    for mdl in ['CAPM', 'FF3', 'Carhart', 'FF5', 'FF6']:
        pre_a = _md_clean(parse_table_row(base_tables / 'table_factor_alphas.tex', mdl, 1))
        post_a = _md_clean(parse_table_row(live_tables / 'table_factor_alphas.tex', mdl, 1))
        pre_t = _md_clean(parse_table_row(base_tables / 'table_factor_alphas.tex', mdl, 2))
        post_t = _md_clean(parse_table_row(live_tables / 'table_factor_alphas.tex', mdl, 2))
        out_lines.append(
            f'| {mdl} | {pre_a or "—"} | {post_a or "—"} | '
            f'{pre_t or "—"} | {post_t or "—"} |'
        )
    out_lines.append('')

    # ── SHAP shares ───────────────────────────────────────────────────────────
    out_lines.append('### SHAP feature importance — table_shap.tex')
    out_lines.append('')
    out_lines.append('| Feature | Pre Overall | Post Overall | Pre Calm | Post Calm | Pre Panic | Post Panic |')
    out_lines.append('|---|---|---|---|---|---|---|')
    for feat in ['Momentum', 'pi_filter']:
        cells_pre = [_md_clean(parse_table_row(base_tables / 'table_shap.tex', feat, i))
                     for i in (1, 2, 3)]
        cells_post = [_md_clean(parse_table_row(live_tables / 'table_shap.tex', feat, i))
                      for i in (1, 2, 3)]
        row = [feat]
        for p, q in zip(cells_pre, cells_post):
            row.extend([p or '—', q or '—'])
        out_lines.append('| ' + ' | '.join(row) + ' |')
    out_lines.append('')

    # ── Step E: leg-betas ────────────────────────────────────────────────────
    out_lines.append('---')
    out_lines.append('')
    out_lines.append('## Part 2 — Leg-betas finding (Step E)')
    out_lines.append('')
    leg_csv = REPO / 'results' / 'leg_betas_by_regime.csv'
    if leg_csv.exists():
        try:
            lb = pd.read_csv(leg_csv)
            out_lines.append('Source: `results/leg_betas_by_regime.csv`')
            out_lines.append('')
            out_lines.append('```')
            out_lines.append(lb.to_string(index=False))
            out_lines.append('```')
            out_lines.append('')
            # Try to extract calm/panic Δβ for M2 XGB
            try:
                m2 = lb[lb.iloc[:, 0].astype(str).str.contains(
                    'M2|XGB', case=False, na=False, regex=True)]
                out_lines.append('### Long − Short β (M2 XGB)')
                out_lines.append('')
                out_lines.append(m2.to_markdown(index=False))
                out_lines.append('')
            except Exception:
                pass
        except Exception as e:
            out_lines.append(f'Could not parse {leg_csv}: {e}')
    else:
        out_lines.append(f'⚠️  Step E output `{leg_csv}` not present yet — '
                          'rerun Step E and re-compose this report.')
    out_lines.append('')

    # ── Inversion classification stub (manual review) ────────────────────────
    out_lines.append('### Inversion classification')
    out_lines.append('')
    out_lines.append('- [ ] **Clean inversion:** long-leg β > short-leg β in calm '
                      'AND long-leg β < short-leg β in panic, both flips '
                      '|Δβ| ≥ 0.3')
    out_lines.append('- [ ] **No clean inversion:** mechanism is cross-sectional '
                      're-ranking of momentum term structure rather than '
                      'beta-exposure channel')
    out_lines.append('')
    out_lines.append('Decided manually after reading the table above.')
    out_lines.append('')

    # ── Sanity gates ─────────────────────────────────────────────────────────
    out_lines.append('---')
    out_lines.append('')
    out_lines.append('## Sanity gates (Shumway shift expected band)')
    out_lines.append('')
    sharpe_pre = maybe_float(parse_table_row(
        base_tables / 'table_performance.tex', M2, 3))
    sharpe_post = maybe_float(parse_table_row(
        live_tables / 'table_performance.tex', M2, 3))
    if sharpe_pre is not None and sharpe_post is not None:
        diff = sharpe_post - sharpe_pre
        verdict = ('within band' if abs(diff) <= 0.05 else
                   'flag' if abs(diff) <= 0.15 else 'ANOMALY')
        out_lines.append(f'- Sharpe shift: {diff:+.3f} (band ±0.05): **{verdict}**')
    out_lines.append('')

    # ── Gate compliance ──────────────────────────────────────────────────────
    out_lines.append('## Gates respected')
    out_lines.append('- ✅ G3: NO `latex/*.tex` edits made.')
    out_lines.append('- ✅ G4: NO `git push` performed.')
    out_lines.append('- ✅ Snapshot intact at `' + str(args.baseline_dir) + '/`.')
    out_lines.append('')

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text('\n'.join(out_lines) + '\n')
    print(f'Wrote: {out_path}')


if __name__ == '__main__':
    main()
