"""
plot_features_hmm.py
====================
Render plots/thesis/features_hmm.png — the four standardised HMM input
features (DD_z, CS_z, DISP_z, REL_N_z) over the full sample with NBER
recession shading.

Reads:  data/panel.parquet  (PANEL_PATH from config.py)
Writes: plots/thesis/features_hmm.{png,pdf}

Promoted out of archive/scripts/regenerate_thesis_plots.py on 2026-05-06
so the figure is regenerated by the canonical pipeline. The companion
regime_probabilities.png is already produced by scripts/hmm_model.py
(Step 1) so the regime-probabilities portion of the archived script is
not reproduced here.
"""

import os
import sys

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from config import PANEL_PATH, PLOTS_THESIS_DIR

PNG_PATH = os.path.join(PLOTS_THESIS_DIR, 'features_hmm.png')
PDF_PATH = os.path.join(PLOTS_THESIS_DIR, 'features_hmm.pdf')

FEATURES_Z = ['DD_z', 'CS_z', 'DISP_z', 'REL_N_z']
FEATURE_LABELS = {
    'DD_z':    'DD (Drawdown)',
    'CS_z':    'CS (BAA-AAA Credit Spread)',
    'DISP_z':  'DISP (Return Dispersion)',
    'REL_N_z': 'REL_N (Market Participation)',
}

NBER_RECESSIONS = [
    ('1973-11-01', '1975-03-01'),
    ('1980-01-01', '1980-07-01'),
    ('1981-07-01', '1982-11-01'),
    ('1990-07-01', '1991-03-01'),
    ('2001-03-01', '2001-11-01'),
    ('2007-12-01', '2009-06-01'),
    ('2020-02-01', '2020-04-01'),
]


def shade_nber(ax):
    for start, end in NBER_RECESSIONS:
        ax.axvspan(pd.Timestamp(start), pd.Timestamp(end),
                   alpha=0.15, color='grey', zorder=0)


def main():
    panel = pd.read_parquet(PANEL_PATH)
    panel = panel.dropna(subset=FEATURES_Z).reset_index(drop=True)
    dates = panel['date']

    fig, axes = plt.subplots(4, 1, figsize=(14, 10), sharex=True)

    for ax, feat in zip(axes, FEATURES_Z):
        ax.plot(dates, panel[feat], linewidth=0.9, color='steelblue')
        ax.set_ylabel(FEATURE_LABELS[feat], fontsize=9)
        ax.axhline(0, color='black', linewidth=0.4, linestyle='--', alpha=0.5)
        shade_nber(ax)
        ax.grid(axis='y', alpha=0.2)
        ax.set_xlim(dates.min(), dates.max())

    axes[-1].set_xlabel('Date', fontsize=10)
    axes[0].set_title('HMM Input Features (standardised, training-sample statistics)',
                      fontsize=12)
    fig.align_ylabels(axes)

    plt.subplots_adjust(hspace=0.08)
    plt.tight_layout()

    os.makedirs(PLOTS_THESIS_DIR, exist_ok=True)
    fig.savefig(PNG_PATH, dpi=150, bbox_inches='tight')
    fig.savefig(PDF_PATH, bbox_inches='tight')
    plt.close(fig)

    print(f'Wrote {PNG_PATH}')
    print(f'Wrote {PDF_PATH}')


if __name__ == '__main__':
    main()
